# Generated by Django 5.1.1 on 2024-09-21 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='lastname',
            new_name='password',
        ),
    ]
