# Generated by Django 5.1.1 on 2024-09-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_natam', '0002_rename_lastname_login_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='birthDay',
        ),
    ]
